django/myform/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('edit/', views.edit, name='edit'),
    path('password/', views.change_password, name='change_password')
]

django/myform/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.create, name='create'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/edit/', views.update, name='update'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:board_pk>/like/', views.like, name='like'),
    path('<int:board_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
]

django/myform/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')), # 꼭 밑에 넣어야 함.
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

django/myform/boards/models.py
from django.db import models
from django.conf import settings


class Board(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_boards', blank=True)
    # AUTH_USER_MODEL : 장고가 기본적으로 갖고 있는 유저 모델
    # blank=True : 값이 없을 수도 있기 때문에(좋아요가 눌리지 않을 수 있기 때문에 설정해줌.)
    # on_delete=models.CASCADE : 회원탈퇴를 하면 작성된 게시글이 함께 삭제 됨.
    def __str__(self):
        return f'글 번호{self.id}, 글 제목 -> {self.title}, 글 내용 -> {self.content}'


# 사용자와 댓글의 관계를 1:N으로 만들어줌.
class Comment(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    # class Meta:
    #     ordering = ('-pk',) # ,를 찍어야 튜플이 됨.
        # 최신 댓글이 상단에 위치하도록 함.

django/myform/boards/forms.py
from django import forms
from .models import Board, Comment

# 게시글의 폼을 설정
class BoardForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        max_length=10,
        widget=forms.TextInput(attrs={
            'class':'title',
            'placeholder':'Enter the title',
        })
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(attrs={
            'class':'content-type',
            'rows':5,
            'cols':50,
            'placeholder':'Enter the content',
        })
    )
    class Meta:
        model = Board
        fields = ['title', 'content']

# 댓글의 폼을 설정
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]


# class BoardForm(forms.Form):
#     title = forms.CharField(
#         max_length=20,
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'class':'title',
#                 'placeholder':'Enter the title'
#             }
#         )
#     )
#     content = forms.CharField(
#         label='내용',
#         widget=forms.Textarea(
#             attrs={
#                 'class':'content-type',
#                 'rows':5,
#                 'cols':50,
#                 'placeholder':'Enter the content'
#             }
#         )
#     )

django/myform/boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from IPython import embed


def index(request):
    # boards = Board.objects.order_by('-id')
    boards = Board.objects.all()[::-1] # 최신글을 상단으로 모든 게시글을 띄운다.
    context = {'boards':boards}
    return render(request, 'boards/index.html', context)

@login_required # 로그인 없이는 글작성을 하지 못하게 함.
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST) # form에 BoardForm틀로 POST요청으로 받은 내용을 담는다
        # embed()
        if form.is_valid(): # form의 유효성검사(True or False)
            # title = form.cleaned_data.get('title') # 딕셔너리형에서 .get('title')의 내용을 추출
            # content = form.cleaned_data.get('content')
            # board = Board.objects.create(title=title, content=content) # 세번째 방법, 저장이 필요없다.
            board = form.save(commit=False)
            board.user = request.user
            board.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm() # form.html의 폼으로(빈 폼)
    context = {'form':form}
    return render(request, 'boards/form.html', context)


def detail(request, board_pk):
    # board = Board.objects.get(pk=board_pk)
    board = get_object_or_404(Board, pk=board_pk)
    # board_pk에 해당하는 글이 있으면 띄우고 아니면 404에러를 띄워
    person = get_object_or_404(get_user_model(), pk=board.user.pk)
    comments = board.comment_set.all() # 게시판에 달린 모든 글을 가져옴.
    comment_form = CommentForm() # 댓글 적는 곳
    context = {'board':board, 'comments':comments, 'comment_form':comment_form, 'person':person}
    return render(request, 'boards/detail.html', context)


def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if board.user == request.user: # board.user : 게시글을 작성한 유저, request.user : 로그인한 사용자
        if request.method == 'POST':
            board.delete()
            return redirect('boards:index')
        else:
            return redirect('boards:detail', board.pk)
    else:
        return redirect('boards:index')


@login_required # 로그인 없이는 글수정을 하지 못하게 함.
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk) # 기존 글을 가져옴.
    if board.user == request.user:
    # board.user : 게시글을 작성한 유저, request.user : 로그인한 사용자/같으면 수정가능, 다르면 index로
        if request.method == 'POST':
            form = BoardForm(request.POST, instance=board)
            if form.is_valid():
                # board.title = form.cleaned_data.get('title')
                # board.content = form.cleaned_data.get('content')
                # board.save()
                form.save()
                return redirect('boards:detail', board.pk)
        else:
            form = BoardForm(instance=board)
            # 초기값 / 이걸 해줘야 글 작성한 내용을 볼 수 있음.
    else:
        return redirect('boards:index')
    context = {'form': form, 'board': board}
    return render(request, 'boards/form.html', context)
    # form이라는 인스턴스 객체를 만들어서 초기값을 설정해주었기 때문에 create.html인데도 수정이 가능함.


@login_required
@require_POST # POST요청을 제외한 요청에는 405에러를 띄운다.
def comments_create(request, board_pk):
    comments_form = CommentForm(request.POST)
    if comments_form.is_valid():
        comment = comments_form.save(commit=False)
        comment.user = request.user
        comment.board_id = board_pk
        comment.save()
    return redirect('boards:detail', board_pk)


@login_required
@require_POST
def comments_delete(request, board_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user != comment.user: # 유저가 댓글을 쓴 유저와 다를 때, detail페이지로 / 아니면 댓글 삭제
        return redirect('boards:detail', board_pk)
    comment.delete()
    return redirect('boards:detail', board_pk)


@login_required
def like(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)

    if request.user in board.like_users.all():
    # 게시글에 좋아요를 누른 모든 유저 중에 어떤 유저가 있다면
        board.like_users.remove(request.user)
        # remove : 중개 테이블에 어떤 유저를 지워준다.(좋아요를 하나 누르면 또 다시 누르지 못하도록)
    else:
        board.like_users.add(request.user)
        # 조건에 맞지 않으면 중개 테이블에 어떤 유저를 넣어준다.
    return redirect('boards:index')


@login_required
def follow(request, board_pk, user_pk):
    person = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user in person.followers.all():
        person.followers.remove(request.user)
    else:
        person.followers.add(request.user)
    return redirect('boards:detail', board_pk)

django/myform/boards/templates/boards/_board.html
<!-- 좋아요 아이콘 표현 -->
<div class="card-body">
    <a href="{% url 'boards:like' board.pk %}" class="card-link">
        {% if user in board.like_users.all %}
            <i class="fas fa-heart fa-lg" style="color:crimson"></i>
        {% else %}
            <i class="far fa-heart fa-lg" style="color:black"></i>
        {% endif %}
    </a>
    <!-- 좋아요 수 -->
    <p class="card-text">{{ board.like_users.count }} 명이 좋아합니다.</p>
</div>

django/myform/boards/templates/boards/_profile.html
<div class="jumbotron text-center text-white bg-dark">
    <p class="lead mb-1">작성자 정보</p> <!-- lead mb-1: p태그 강조할 때 사용 -->
    <h2 class="display">{{ board.user }}</h2>
    <hr class="border-white"> <!-- 구분선 -->
    <p class="lead">
        팔로잉: {{ person.followings.all | length }}
        팔로워: {{ person.followers.all | length }}
    </p>
    {% if user != person %}
        {% if user in person.followers.all %}
            <a class='btn btn-primary' href="{% url 'boards:follow' board.pk person.pk %}" role="button">Unfollow</a>
        {% else %}
            <a class='btn btn-primary' href="{% url 'boards:follow' board.pk person.pk %}" role="button">Follow</a>
        {% endif %}
    {% endif %}
</div>

django/myform/boards/templates/boards/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!-- bit.do/fontawesome-haha -->
    {% bootstrap_css %}
    <title></title>
</head>
<body>
    <div class="container">
        {% if user.is_authenticated %}
            <h1>안녕, {{ user.username }}</h1>
            <a href="{% url 'accounts:edit' %}"><input type="button" value="회원정보수정"></a><br>
            <a href="{% url 'accounts:change_password' %}"><input type="button" value="비밀번호변경"></a>
            <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="로그아웃">
            </form>
            <form action="{% url 'accounts:delete' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="회원탈퇴">
            </form>
            <hr>
        {% else %}
            <a href="{% url 'accounts:login' %}">[로그인]</a>
            <a href="{% url 'accounts:signup' %}">[회원가입]</a>
        {% endif %}

        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

django/myform/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}

{% block body %}
    <h1>DETAIL</h1>
    <hr>
    <h2>{{ board.pk }}번 글</h2>
    <p>제목: {{ board.title }}</p>
    <p>내용: {{ board.content }}</p>
    <p>작성 시각: {{ board.created_at }}</p>
    <p>수정 시각: {{ board.updated_at }}</p>
    <hr>

    <h3>댓글</h3>
    {% for comment in comments|dictsortreversed:'pk' %} <!-- pk를 기준으로 최신 댓글이 상단에 위치하도록 -->
        <p><b>{{ comment.user }}님의 댓글: {{ comment.content }}</b></p>
        {% if user == comment.user %} <!-- 댓글을 쓴 유저에게만 댓글 삭제 버튼이 보이도록 -->
            <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
            {% csrf_token %}
                <input type="submit" value="댓글삭제">
            </form>
        {% endif %}
    {% empty %}
        <p><b>댓글이 없네유 ㅠㅠㅠㅠㅠㅠ</b></p>
    {% endfor %}
    <hr>
    {% include 'boards/_profile.html' %} <!-- 모듈화 -->
    <hr>
    <h3>댓글 작성</h3>
    {% if user.is_authenticated %}
        <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <input type="submit" value="댓글작성">
        </form>
    {% else %}
        <a href="{% url 'accounts:login' %}">댓글쓰려면 로그인</a>
    {% endif %}

    <hr>
    <a href="{% url 'boards:index' %}">[메인 페이지]</a>

    {% if user == board.user %} <!-- 게시글을 작성한 유저만 수정, 삭제할 수 있도록 -->
        <a href="{% url 'boards:update' board.pk %}">[수정]</a><br>
        <form action="{% url 'boards:delete' board.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    {% endif %}
{% endblock %}

django/myform/boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% load bootstrap4 %}

{% block body %}

{% if request.resolver_match.url_name == 'create' %}
<!-- urls.py에서 name이 create일때... -->
    <h1>CREATE</h1>
{% else %}
    <h1>UPDATE</h1>
{% endif %}
<hr>

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button "글작성" button_type='submit' button_class='btn-danger' %}
<!--    {{ form.as_p }}-->
    <!-- views.py에서 온 else분기의 form에 담은 내용을 p태그로 담는다. -->
<!--    <input type="submit" value="Submit"><br>-->
</form>
<hr>
{% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'boards:index' %}" class="btn btn-primary">메인페이지</a>
{% else %}
    <a href="{% url 'boards:detail' board.pk %}" class="btn btn-primary">상세</a>
{% endif %}
{% endblock %}

django/myform/boards/templates/boards/index.html
{% extends 'boards/base.html' %}

{% block body %}
    <h1>INDEX</h1>
    <hr>
    {% for board in boards %}
        <p><b>작성자: {{ board.user }}</b></p>
        <p>번호: {{ board.pk }}</p>
        <p>제목: {{ board.title }}</p>
        <a href="{% url 'boards:detail' board.pk %}">[상세]</a>
        {% include 'boards/_board.html' %}
        <hr>
    {% endfor %}
    <hr>
    {% if user.is_authenticated %}
        <a href="{% url 'boards:create' %}">[새 글]</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">[글을 작성하려면 로그인 해주세요.]</a>
    {% endif %}
{% endblock %}