django/crud_review/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'), # name='별명'
    path('new/', views.new, name='new'),
    path('<int:board_pk>/', views.detail, name='detail'), # 정수의 pk라는 변수에 담겠다.
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.edit, name='edit'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/edit/', views.comments_edit, name='comments_edit'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

django/crud_review/crud_review/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/crud_review/boards/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

def board_image_path(instance, filename):
    return f'boards/{instance.pk}번글/images/{filename}'

class Board(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = ProcessedImageField(
        upload_to=board_image_path,
        processors=[Thumbnail(200,300)],
        format='JPEG',
        options={'quality':90}
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    content = models.CharField(max_length=200) # 댓글의 내용
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE) # 댓글에 해당하는 게시글을 나타낸다.

    def __str__(self):
        return f'<Board{self.board_id}: Comment({self.id} - {self.content})>'

    # 생성 후
    # $ python manage.py makemigrations
    # $ python manage.py migrate

django/crud_review/boards/views.py
from django.shortcuts import render, redirect
from .models import Board, Comment # 같은 경로에 있는 models.py에서 Board 클래스를 import

def index(request):
    # boards = Board.objects.order_by('-id') # django ORM으로 내림차순 정렬
    boards = Board.objects.all()[::-1] # python으로 내림차순 정렬
    context = {'boards':boards}
    return render(request, 'boards/index.html', context)

def new(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        board = Board(title=title, content=content, image=image)  # column들의 이름 : 변수
        board.save()  # DB에 저장

        # return render(request, 'boards/create.html') # 글을 작성하고 제출하면 '작성완료'창으로 이동
        return redirect('boards:detail', board.pk)
    else:
        return render(request, 'boards/create.html')


def detail(request, board_pk): # 글을 작성하면 그 글로
    board = Board.objects.get(pk=board_pk)
    comments = board.comment_set.all()
    context = {'board':board, 'comments':comments}
    return render(request, 'boards/detail.html', context)

def delete(request, board_pk): # variable routing? 특정값을 변수화하여 인자로 넘기기 위해(pk)
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)


def edit(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.image = request.FILES.get('image')
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        context = {'board':board}
        return render(request, 'boards/edit.html', context)


def comments_create(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        comment = Comment()
        comment.board_id = board.pk
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('boards:detail', board.pk)
    else:
        return redirect('boards:detail', board.pk)

def comments_edit(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('boards:detail', board_pk)
    else:
        context = {'comment':comment}
        return render(request, 'boards/comments_edit.html', context)


def comments_delete(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.delete()
        return redirect('boards:detail', board_pk)
    else:
        return redirect('boards:detail', board_pk)

django/crud_review/boards/templates/boards/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'boards/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'boards/favicon/favicon.ico' %}" type="image/x-icon">
    <title>CRUD Review</title>
</head>
<body>
    <img src="{% static 'ddung.jpg' %}" alt="ddung">
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

django/crud_review/boards/templates/boards/comments_edit.html
{% extends 'boards/base.html' %}

{% block body %}
    <h1 class="text-center">Comment Edit</h1>
    <hr>
    <form action="" method="POST">
        {% csrf_token %}
        댓글 수정: <input type="text" name="content" value="{{ comment.content }}">
        <input type="submit" value="댓글 수정">
    </form>
{% endblock %}

django/crud_review/boards/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% load static %}
{% block body %}
    <h1 class="text-center">DETAIL</h1>
    <h2>{{ board.pk }}번째 글</h2>
    <hr>
    <p>글 제목: {{ board.title }}</p>
    <p>글 내용: {{ board.content }}</p>
    <p>글 작성 시각: {{ board.created_at }}</p>
    <p>글 수정 시각: {{ board.updated_at }}</p>
    <hr>

    <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {% csrf_token %}
        댓글: <input type="text" name="content">
        <input type="submit" value="등록">
    </form>

    <hr>
        <p><b>댓글 목록 | 댓글 개수: {{ comments|length }}</b></p>
        {% for comment in comments %}
            <li>{{ comment.content }}</li>
            <a href="{% url 'boards:comments_edit' board.pk comment.pk %}">[수정]</a>
            <form action="{% url 'boards:comments_delete' board.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
        {% empty %}
            <p><b>[empty]</b></p>
        {% endfor %}
    <hr>
    {% if board.image %}
            <img src="{{ board.image.url }}" alt="{{ board.image }}">
    {% else %}
        <img src="{% static '풍경.jpg' %}" alt="">
    {% endif %}
    <hr>
    <a href="{% url 'boards:edit' board.pk %}">[수정]</a><br>
    <a href="{% url 'boards:index' %}">[목록]</a>
    <form action="{% url 'boards:delete' board.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>

{% endblock %}

django/crud_review/boards/templates/boards/edit.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">EDIT</h1>
<hr>
    <p><b>기존 이미지</b></p>
    {% if board.image %}
        <img src="{{ board.image.url }}" alt="{{ board.image }}">
    {% endif %}
<hr>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">Title</label><br>
    <input type="text" name="title" id="title" value="{{ board.title }}"><br>
    <label for="content">Content</label><br>
    <textarea name="content" id="content" cols="30" rows="10">{{ board.content }}</textarea><br>
    <label for="image">Image</label>
    <input type="file" name="image" id="image" accept="image/*"><br>
    <input type="submit" value="Submit">
</form>
<a href="{% url 'boards:index' %}">[메인 페이지]</a>
{% endblock %}

django/crud_review/boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% load static %} <!-- 이미지가 어디에 위치해 있는지 알려주는 태그 -->
{% block body %}
<h1 class="text-center">BAEK</h1>
<img src="{% static 'boards/images/urban.jpg' %}" alt="urban">
<hr>
{% for board in boards %}
    <p>글 번호: {{ board.pk }}</p>
    <p>글 제목: {{ board.title }}</p>
    <a href="{% url 'boards:detail' board.pk %}">[상세 보기]</a>
    <hr>
{% endfor %}
<a href="{% url 'boards:new' %}">[글 작성]</a>
{% endblock %}

django/crud_review/boards/templates/boards/new.html
{% extends 'boards/base.html' %}

{% block body %}
<h1 class="text-center">NEW</h1>
<hr>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">Title</label><br>
    <input type="text" name="title" id="title"><br>
    <label for="content">Content</label><br>
    <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
    <label for="image">Image</label><br>
    <input type="file" name="image" id="image" accept="image/*">
    <input type="submit" value="Submit">
</form>
<a href="{% url 'boards:index' %}">[메인 페이지]</a>
{% endblock %}