django/bestspot/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns= [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('edit/', views.edit, name='edit'),
    path('password/', views.change_password, name='change_password'),
]

django/bestspot/bestspot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('bs/', include('bs.urls')),
    path('admin/', admin.site.urls),
]

django/bestspot/bs/urls.py
from django.urls import path
from . import views

app_name = 'bs'

urlpatterns = [
    path('', views.intro, name='intro'),
    path('new/', views.new, name='new'),
    path('map_1/', views.map_1, name='map_1'),
    path('map_2/', views.map_2, name='map_2'),
    path('<int:history_pk>/', views.detail, name='detail'),
    path('<int:history_pk>/calculate/', views.calculate, name='calculate'),
    path('<int:history_pk>/edit/', views.update, name='update'),
    path('<int:history_pk>/delete/', views.delete, name='delete'),
]

django/bestspot/bs/models.py
from django.db import models
from django.conf import settings

class BS(models.Model):
    year = models.IntegerField()
    month = models.IntegerField()
    day = models.IntegerField()
    hour = models.IntegerField()
    min = models.IntegerField()
    title = models.CharField(max_length=20)
    member = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'날짜: {self.year}년 {self.month}월 {self.day}일 {self.hour}시 {self.min}분 {self.member}명'

class BS2(models.Model):
    weight = models.IntegerField(blank=True)
    start = models.CharField(max_length=20)
    goal_lat = models.FloatField()
    goal_lng = models.FloatField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Cost(models.Model):
    cost = models.IntegerField()

    def __str__(self):
        return f'총 결제금액: {self.cost}원'

django/bestspot/bs/forms.py
from django import forms
from .models import BS, BS2, Cost

year_choices = [tuple([x,x]) for x in range(2019,2031)]
month_choices = [tuple([x,x]) for x in range(1,13)]
day_choices = [tuple([x,x]) for x in range(1,32)]
hour_choices = [tuple([x,x]) for x in range(0,24)]
min_choices = [tuple([x,x]) for x in range(0,60,10)]
member_choices = [tuple([x,x]) for x in range(2,21)]
weight_choices = [tuple([x,x]) for x in range(1,11)]

class BSForm(forms.ModelForm):
    title = forms.CharField(
        label='모임명',
        max_length=20,
        widget=forms.TextInput(attrs={
            'class': 'title',
        })
    )
    year = forms.IntegerField(label="년도",
                              widget=forms.Select(choices=year_choices)
    )
    month = forms.IntegerField(label="월",
                              widget=forms.Select(choices=month_choices)
    )
    day = forms.IntegerField(label="일",
                              widget=forms.Select(choices=day_choices)
    )
    hour = forms.IntegerField(label="시",
                              widget=forms.Select(choices=hour_choices)
    )
    min = forms.IntegerField(label="분",
                              widget=forms.Select(choices=min_choices)
    )
    member = forms.IntegerField(label="인원수",
                                  widget=forms.Select(choices=member_choices)
    )

    class Meta:
        model = BS
        fields = ['title','year','month','day','hour','min','member']

class BS2Form(forms.ModelForm):#
    weight = forms.IntegerField(label="가중치",
                              widget=forms.Select(choices=weight_choices)
    )
    start = forms.CharField(
        label='출발지',
        max_length=10,
        widget=forms.TextInput(attrs={
            'class':'start',
        })
    )
    goal = forms.CharField(
        label='목적지',
        max_length=10,
        widget=forms.TextInput(attrs={
            'class':'goal',
        })
    )
    class Meta:
        model = BS2
        fields = ['weight','start','goal']

class CostForm(forms.ModelForm):
    cost = forms.IntegerField(
        label='총 결제비용',
        widget=forms.NumberInput(attrs={
            'class':'cost',
        })
    )
    class Meta:
        model = Cost
        fields = ['cost']

django/bestspot/bs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .models import BS, BS2, Cost
from .forms import BSForm, BS2Form, CostForm
import googlemaps
import pandas as pd
import numpy as np
import math
from haversine import haversine
from IPython import embed
import os
from django.conf import settings

def intro(request):
    # histories = BS.objects.all()[::-1]
    histories = BS.objects.order_by('-pk')
    context = {'histories': histories}
    return render(request, 'bs/intro.html', context)

@login_required
def new(request):
    # bs_map = get_object_or_404(BS, pk=history_pk) # 객체
    bs_map = BS.objects.order_by('-pk') # 쿼리셋
    counter = []
    if request.method == 'POST':
        form = BSForm(request.POST)
        if form.is_valid():
            history = form.save(commit=False)
            history.user = request.user
            mem_count = history.member
            history.save()
            for i in range(1, mem_count+1):
                counter.append(i)
            context = {
                'bs_map': bs_map,
                'counter': counter
            }
            return render(request,'bs/map_1.html', context)
    else:
        form = BSForm()
    context = {'form': form}
    return render(request, 'bs/form.html', context)

# def map_1(request, history_pk):
#     bs_map = get_object_or_404(BS, pk=history_pk)
#     if request.method == 'POST':
#         form = BS2Form(request.POST)
#         if form.is_valid():
#             history = form.save(commit=False)
#             history.user = request.user
#             history.save()
#             # context = {'bs_map':bs_map}
#             return redirect('bs:match', history.pk)
#     else:
#         form = BS2Form()
#     context = {'form': form, 'counter': range(1, bs_map.member+1)}
#     return render(request, 'bs/map_1.html', context)
#     # return render(request, 'bs/form.html', context)

def map_1(request):
    gmaps_key = "*****"
    gmaps = googlemaps.Client(key=gmaps_key)
    lat_sum = 0
    lng_sum = 0
    user_lat = []
    user_lng = []

    start = request.POST.getlist('start[]')
    weight = request.POST.getlist('weight[]')
    sum_weight = 0
    for i in weight:
        sum_weight += int(i)


    match_mem = len(start) # 인원수(member)

    for i in start:
        user_info = gmaps.geocode(i, language='ko')
        user_geo = user_info[0].get('geometry')
        user_lat.append(user_geo['location']['lat'])  # 사용자가 입력한 위치의 위도값의 집합
        user_lng.append(user_geo['location']['lng'])  # 사용자가 입력한 위치의 경도값의 집합

    for i in range(match_mem):
        lat_sum += float(user_lat[i]) * float(weight[i])
        lng_sum += float(user_lng[i]) * float(weight[i])

    lat_avg = lat_sum / sum_weight
    lng_avg = lng_sum / sum_weight
    match1 = (lat_avg, lng_avg) # 1차 매칭 위치의 경위도값


    # 지하철역 출력
    station_name = []  # 지하철역 집합 리스트
    station = pd.read_excel(os.path.join(settings.BASE_DIR, 'subway_all.xlsx'), encoding='utf-8')['역이름']
    for name in station:
        station_name.append(name + '역')

    # 지하철역과 사용자의 평균 위치의 차이 출력
    dic_all = []  # 거리 차이의 집합 리스트
    # for i in station_name: # 전체 600개
    for i in station_name: # 테스트용 100개
        try:
            station_info = gmaps.geocode(i, language='ko')
            station_geo = station_info[0].get('geometry')
            station_lat = station_geo['location']['lat']  # 위도
            station_lng = station_geo['location']['lng']  # 경도
            station_loc = (station_lat, station_lng)  # 위도, 경도를 담은 튜플
            distance = haversine(match1, station_loc)  # 사용자들의 평균 위치와 역 간의 거리
            dic_all.append(distance) # 거리 차의 집합
        except IndexError:
            if i == '동대문역':
                station_lat = 37.571697
                station_lng = 127.01086
                station_loc = (station_lat, station_lng)  # 위도, 경도를 담은 튜플
                distance = haversine(match1, station_loc)  # 사용자들의 평균 위치와 역 간의 거리
                dic_all.append(distance)
            elif i == '삼양역':
                station_lat = 37.626985
                station_lng = 127.018141
                station_loc = (station_lat, station_lng)  # 위도, 경도를 담은 튜플
                distance = haversine(match1, station_loc)  # 사용자들의 평균 위치와 역 간의 거리
                dic_all.append(distance)
            else:  # 4.19 묘지역
                station_lat = 37.64942
                station_lng = 127.013708
                station_loc = (station_lat, station_lng)  # 위도, 경도를 담은 튜플
                distance = haversine(match1, station_loc)  # 사용자들의 평균 위치와 역 간의 거리
                dic_all.append(distance)

    x = dict(zip(station_name, dic_all)) # {'지하철역': 역과 1차 매칭 지점 간의 거리 차이}
    sort = sorted(x.items(), key=lambda t: t[1])[0:5] # 가까운 순으로 5곳의 지하철역 출력


    best = BS2()
    # start -> 리스트 [강남역, 역삼역]
    start.append("center")
    # start -> 리스트 [강남역, 역삼역, center]
    # user_lat # 리스트 [강남역 위도, 역삼역 위도]
    # user_lng # 리스트 [강남역 경도, 역삼역 경도]
    user_lat.append(lat_avg) # 리스트 [강남역 위도, 역삼역 위도, 중심지점 위도]
    user_lng.append(lng_avg) # 리스트 [강남역 경도, 역삼역 경도, 중심지점 경도]


    for i in range(len(sort)):
        start.append(sort[i][0])
        # 리스트[강남역, 역삼역, center, 역이름 1 ~ 5]
        user_lat.append(gmaps.geocode(sort[i][0], language='ko')[0].get('geometry')['location']['lat'])
        # 리스트 [강남역 위도, 역삼역 위도, 중심지점 위도, 위도 1 ~ 5]
        user_lng.append(gmaps.geocode(sort[i][0], language='ko')[0].get('geometry')['location']['lng'])
        # 리스트 [강남역 경도, 역삼역 경도, 중심지점 경도, 경도 1 ~ 5]

    sort_name = start[-6:] # [center, 역이름 1 ~ 5]
    sort_lat = user_lat[-6:]  # [center, 역 1 ~ 5 위도]
    sort_lng = user_lng[-6:]  # [center, 역 1 ~ 5 경도]
    start_lat = user_lat[:-7] # [강남역 위도, 역삼역 위도]
    start_lng = user_lng[:-7] # [강남역 경도, 역삼역 경도]
    best.start = start # [강남역, 역삼역, center, 역이름 1 ~ 5]
    best.weight = weight # [1, 1]
    best.goal_lat = user_lat # [강남역 위도, 역삼역 위도, 중심지점 위도, 위도 1 ~ 5]
    best.goal_lng = user_lng # [강남역 경도, 역삼역 경도, 중심지점 경도, 경도 1 ~ 5]


    context = {
        'best': best,
        'sort_name': sort_name,
        'sort_lat': sort_lat,
        'sort_lng': sort_lng,
        'center_lat': user_lat[-6],
        'center_lng': user_lng[-6],
        'start_lat': user_lat[:-7],
        'start_lng': user_lng[:-7],
    }
    return render(request, 'bs/map_2.html', context)

    # for i in range(len(sort)):
    #     sort_info = gmaps.geocode(f'sort[i][0]', language='ko')
    #     sort_geo = sort_info[0].get('geometry')
    #     sort_lat = sort_geo['location']['lat']  # 위도
    #     sort_lng = sort_geo['location']['lng']  # 경도
    #     start.append(sort[i][0])

# def map_1(request):
#     if request.method == 'POST':
#         form = BS2Form(request.POST)
#         if form.is_valid():
#             history = form.save(commit=False)
#             history.save()
#             return render(request, 'bs/map_2.html')
#     else:
#         form = BS2Form()
#     context = {'form': form}
#     return render(request, 'bs/form.html', context)

# def center(x,y):
#     gmaps_key = "AIzaSyCYmb7K-OhKPh2JlvpRQKhYOnoIqCcKUSw"
#     gmaps = googlemaps.Client(key=gmaps_key)
#     lat_sum = 0
#     lng_sum = 0
#     weight = []
#     person = []
#     for i in map_1.history.member:
#         start_info = gmaps.geocode(person[i], language='ko')
#         start_geo = start_info[0].get('geometry')
#         start_lat = start_geo['location']['lat']
#         start_lng = start_geo['location']['lng']
#         lat_sum += start_lat * weight[i]
#         lng_sum += start_lng * weight[i]
#         # print(f'{i + 1}번 사용자', person[i], "위도: ", start_lat, "경도: ", start_lng)
#         # print('-----------------------------------------------')
#
#     lat_avg = lat_sum / sum(weight)
#     lng_avg = lng_sum / sum(weight)
#     center = (lat_avg, lng_avg)
#     # print('평균 위치:', loc_avg)  # 사용자들의 평균 위도&경도


def map_2(request, history_pk):
    history3 = get_object_or_404(BS2, pk=history_pk)
    request.POST.get()
    history3.save()
    context = {'history3': history3}
    return render(request, 'bs/form.html', context)


def detail(request, history_pk):
    history = get_object_or_404(BS, pk=history_pk)
    context = {'history':history}
    return render(request, 'bs/detail.html', context)

def update(request, history_pk):
    history = get_object_or_404(BS, pk=history_pk)
    if request.method == 'POST':
        form = BSForm(request.POST, instance=history)
        if form.is_valid():
            form.save()
            return redirect('bs:detail', history.pk)
    else:
        form = BSForm(instance=history)
    context = {'form':form, 'history':history}
    return render(request, 'bs/form.html', context)

def delete(request, history_pk):
    history = get_object_or_404(BS, pk=history_pk)
    if request.method == 'POST':
        history.delete()
        return redirect('bs:intro')
    else:
        return redirect('bs:detail')

def calculate(request, history_pk):
    history = get_object_or_404(BS, pk=history_pk)
    if request.method == 'POST':
        form = CostForm(request.POST, instance=history)
        if form.is_valid():
            form.save()
            return redirect('bs:calculate', history.pk)
    else:
        form = CostForm(instance=history)
    context = {'form':form, 'history':history}
    return render(request, 'bs/calculate.html', context)

django/bestspot/bs/templates/bs/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://kit.fontawesome.com/eb4e6c57f5.js"></script>
    {% bootstrap_css %}
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif+KR:200,300,400,500,600,700,900&display=swap&subset=korean" rel="stylesheet">
<style>
      p {
        font-family: 'Noto Serif KR', serif;
        font-size: 23px;
      }
      p.a {
        font-weight: 400;
      }
      p.b {
        font-weight: 700;
      }
      p.c {
        font-weight: 800;
      }
      p.d {
        font-weight: bold;
      }
</style>

    <title>BS Form</title>
</head>
<body>
    <div class="container">
        {% if user.is_authenticated %}
            <h1>Hi, {{ user.username }}</h1>
            <a href="{% url 'accounts:edit' %}" class="btn btn-dark">회원정보변경</a>
            <a href="{% url 'accounts:change_password' %}" class="btn btn-dark">비밀번호변경</a>
            <form action="{% url 'accounts:logout' %}" method="POST" style="width:95px;float:left;" data-toggle="modal">
                {% csrf_token %}
                <input type="submit" value="로그아웃" class="btn btn-dark">
            </form>
            <form action="{% url 'accounts:delete' %}" method="POST" style="width:95px;float:left;" data-toggle="modal">
                {% csrf_token %}
                <input type="submit" value="회원탈퇴" class="btn btn-dark">
            </form>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="btn btn-dark">로그인</a>
            <a href="{% url 'accounts:signup' %}" class="btn btn-dark">회원가입</a>
        {% endif %}
        <hr>
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

django/bestspot/bs/templates/bs/calculate.html
{% extends 'bs/base.html' %}
{% block body %}
    <h1 class="text-center">Calculate</h1>
    <hr>
    <form action="{% url 'bs:calculate' history.pk %}" method="POST">
        {% csrf_token %}
        <label for="Cost">Cost</label><br>
        <input type="text" name="Cost" id="Cost">
        <input type="submit" value="정산" class="btn btn-primary">
    </form>
    <a href="{% url 'bs:detail' history.pk %}" class="btn btn-dark">뒤로가기</a>
{% endblock %}

django/bestspot/bs/templates/bs/detail.html
{% extends 'bs/base.html' %}
{% block body %}
<link href="https://fonts.googleapis.com/css?family=Noto+Serif+KR:200,300,400,500,600,700,900&display=swap&subset=korean" rel="stylesheet">
<style>
      p {
        font-family: 'Noto Serif KR', serif;
        font-size: 23px;
      }
      p.a {
        font-weight: 400;
      }
      p.b {
        font-weight: 700;
      }
      p.c {
        font-weight: 800;
      }
      p.d {
        font-weight: bold;
      }
</style>
<h1 class="text-center"><p class="d"><font size="50px;">DETAIL</font></p></h1>
<hr>
<h2><p class="d"><b>모임명: {{ history.title }}</b></p></h2>
<p>일정: {{ history.year }}년 {{ history.month }}월 {{ history.day }}일 {{ history.hour }}시 {{ history.min }}분</p>

<p>인원수: {{ history.member }}</p>
<p>목적지: {{ history.goal }}</p>

<hr>

<a href="{% url 'bs:calculate' history.pk %}" class="btn btn-primary">정산</a>
<a href="{% url 'bs:update' history.pk %}" class="btn btn-primary">수정</a>
<a href="{% url 'bs:intro' %}" class="btn btn-primary">목록</a>
<a href="{% url 'bs:delete' history.pk %}" class="btn btn-danger">삭제</a>
{% endblock %}

django/bestspot/bs/templates/bs/form.html
{% extends 'bs/base.html' %}
{% load bootstrap4 %}
{% block body %}


{% if request.resolver_match.url_name == 'new' %}
<h1 class="text-center">NEW</h1>
{% else %}
<h1 class="text-center">UPDATE</h1>
{% endif %}
<hr>

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% bootstrap_button "모임결성" button_type='submit' button_class='btn-outline-dark' %}
</form>

{% if request.resolver_match.url_name == 'new' %}
<a href="{% url 'bs:intro' %}" class="btn btn-dark">작성취소</a>
{% else %}
<a href="{% url 'bs:detail' history.pk %}" class="btn btn-dark">수정취소</a>
{% endif %}
{% endblock %}

django/bestspot/bs/templates/bs/intro.html
{% extends 'bs/base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block body %}

<link href="https://fonts.googleapis.com/css?family=Noto+Serif+KR:200,300,400,500,600,700,900&display=swap&subset=korean" rel="stylesheet">
<style>
      p {
        font-family: 'Noto Serif KR', serif;
        font-size: 23px;
      }
      p.a {
        font-weight: 400;
      }
      p.b {
        font-weight: 700;
      }
      p.c {
        font-weight: 800;
      }
      p.d {
        font-weight: bold;
      }
</style>
    <h1 class="text-center"><p class="d"><font size="50px;">INTRO</font></p></h1>
    <hr>
    {% for history in histories %}
        <p><b>모임명: {{ history.title }}</b></p>
        <p>일정: {{ history.year }}년 {{ history.month }}월 {{ history.day }}일 {{ history.hour }}시 {{ history.min }}분</p>
        <a href="{% url 'bs:detail' history.pk %}" class="btn btn-dark btn-sm"><p class="a"><font size="3px;">모임 상세보기</font></p></a>
        <hr>
    {% endfor %}

    <a href="{% url 'bs:new' %}" class="btn btn-primary btn-sm"><p class="a"><font size="3px;">새 모임</font></p></a>
<hr>
{% endblock %}

django/bestspot/bs/templates/bs/map_1.html
{% extends 'bs/base.html' %}
{% block body %}

    <link href="https://fonts.googleapis.com/css?family=Noto+Serif+KR:200,300,400,500,600,700,900&display=swap&subset=korean" rel="stylesheet">
<style>
      p {
        font-family: 'Noto Serif KR', serif;
        font-size: 23px;
      }
      p.a {
        font-weight: 400;
      }
      p.b {
        font-weight: 700;
      }
      p.c {
        font-weight: 800;
      }
      p.d {
        font-weight: bold;
      }
</style>


<h1 class="text-center"><p class="a"><font size="50px;">어디서?</font></p></h1>
<br>
<fieldset>
<legend><p class="a"><font size="6px;">중간지점찾기</font></p></legend>
    <form action="{% url 'bs:map_1' %}" method="POST">
        {% csrf_token %}
        {% for i in counter %}
            <div class="text-center">
                <label for="start"><p class="a"><font size="4px;">{{ i }}번 출발지: </font></p></label>
                <input type="text" name="start[]" id="start" size="40">
                <label for="weight"><p class="a"><font size="4px;">{{ i }}번 가중치: </font></p></label>
                <input type="number" name="weight[]" id="weight" min="1" max="5">
            </div>
        {% endfor %}
        <p class="a"><input type="submit" value="입력" style="float:right;" class="btn btn-primary"></p>
    </form>
</fieldset>
<a href="{% url 'bs:new' %}" class="btn btn-dark">뒤로가기</a>
<a href="{% url 'bs:intro' %}" class="btn btn-dark">작성취소</a>
<hr>
{% endblock %}

django/bestspot/bs/templates/bs/map_2.html
{% extends 'bs/base.html' %}

{% block body %}
<h1 class="text-center">여기서 보자</h1>
<hr>
<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=xg73rbbnga"></script>
<div id="map" style="width:100%;height:400px;"></div>

<script>
    var mapOptions = {
        center: new naver.maps.LatLng({{ center_lat }}, {{ center_lng }}),
        zoom: 7
    };
    var map = new naver.maps.Map('map', mapOptions);
    {{dic. }}
    var x = {{ sort_lat }};
    var y = {{ sort_lng }};

   function drawNaverMarker(x,y){
      var marker = new naver.maps.Marker({
          map: map,
          position: new naver.maps.LatLng(y, x),
      });
   }
    function drawNaverMarker2(x,y){
        var marker2 = new naver.maps.Marker({
            map: map,
            position: new naver.maps.LatLng(y, x),
            icon: {
                path: [
                    new naver.maps.Point(10, 70), new naver.maps.Point(20, 100), new naver.maps.Point(30, 70),
                ],
                style: "closedPath",
                fillColor: '#ff0000',
                fillOpacity: 1,
                strokeColor: '#000000',
                strokeStyle: 'solid',
                strokeWeight: 1
            }
        });

        var contentString = [
            '<div class="iw_inner">',
            '   <h4>1차 매칭 지점</h4>',
            '</div>'
        ].join('');

        var infowindow = new naver.maps.InfoWindow({
            content: contentString
        });

        infowindow.open(map, marker2);
    }
    drawNaverMarker2(y[0],x[0])
    for(i=1; i<x.length; i++){
        drawNaverMarker(y[i],x[i])
    }


</script>
<div>
    <form action="{% url 'bs:map_2' %}">
        <fieldset style="float:right; position: relative; left: -50%;">
            <legend>근접 지하철역</legend>
            {% for i in sort_name|slice:"1:" %}
                <label class="checkbox">
                    <input type="checkbox" name="goal" value="{{ i }}">{{ i }}
                </label><br>
            {% endfor %}
            <input type="submit" value="NEXT">
        </fieldset>
    </form>
</div>
{% endblock %}